name: Test on Paper 1.14.2 GraalVM

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build release
        run: npm run build:dist
      - name: Run the tests in Docker
        run: docker build . --file SMA/Dockerfile-paper-1.14.2-graalvm --tag magikcraft:$(date +%s)
