name: Test on Paper 1.14.2 JDK 8

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml
      - name: Build release
        run: |
          mkdir -p magikcraft/scriptcraft
          mv target/js/* magikcraft/scriptcraft/
          cp -r src/main/js/* magikcraft/scriptcraft/
          cp -r SMA/sma-bootstrap magikcraft/scriptcraft/plugins
          mkdir -p magikcraft/scriptcraft-plugins/__jasmine
          cp -r SMA/__jasmine/* magikcraft/scriptcraft-plugins/__jasmine/
          cp SMA/*.md magikcraft/
          cp target/scriptcraft.jar magikcraft/magik-scriptcraft.jar
      - name: Run the tests in Docker
        run: docker build . --file SMA/Dockerfile-paper-1.14.2-jdk8 --tag magikcraft:$(date +%s)
