name: Create Magikcraft Test Containers

on:
  - repository_dispatch
jobs:
  package:
    runs-on: ubuntu-latest
    if: github.event.action == 'TYPE_TEST_MAGIKCRAFT'
    steps:
      - uses: actions/checkout@v2
      - name: Archive Dockerfile
        uses: actions/upload-artifact@v1
        with:
          name: SMA
          path: SMA
  docker:
    name: Publish Docker images
    needs: package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        minecraft: [paper-1.14.4, paper-1.15.2]
        vm: [graalvm, openjdk8]
    steps:
      - name: Download build for job 2
        uses: actions/download-artifact@v1
        with:
          name: build
      - name: Download Dockerfile for job 2
        uses: actions/download-artifact@v1
        with:
          name: SMA
      - name: Publish Docker image to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.12
        with:
          name: magikcraft/magikcraft
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: SMA/Dockerfile-Magikcraft
          buildargs: image_tag=${{matrix.minecraft}}-${{matrix.vm}}-test
          tags: "${{matrix.minecraft}}-${{matrix.vm}}-test"
  dockerNukkit:
    name: Publish Docker images
    needs: package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        minecraft: [nukkit-1.0, nukkit-2.0]
        vm: [graalvm, openjdk8]
    steps:
      - name: Download build for job 3
        uses: actions/download-artifact@v1
        with:
          name: build
      - name: Download Dockerfile for job 3
        uses: actions/download-artifact@v1
        with:
          name: SMA
      - name: Publish Docker image to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.12
        with:
          name: magikcraft/magikcraft
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: SMA/Dockerfile-Nukkit-Scriptcraft-release
          buildargs: image_tag=${{matrix.minecraft}}-${{matrix.vm}}-test
          tags: "${{matrix.minecraft}}-${{matrix.vm}}-test"
  report_success:
    runs-on: ubuntu-latest
    needs: [docker, dockerNukkit]
    steps:
      - name: Tell Camunda Cloud What's up!
        uses: jwulf/zeebe-action@master
        with:
          clientConfig: ${{ secrets.ZEEBE_CLIENT_CONFIG }}
          operation: publishMessage
          messageName: MAGIKCRAFT_TEST_CONTAINERS_BUILT
          correlationKey: ${{ github.event.client_payload.buildid }}
          variables: '{"test_containers_published": "true"}'
